### PR TITLE
5 social options

### PR DESCRIPTION
**Pull request by hcpss-banderson**
This is an attempt at a fix for #5

### CODE REVIEW

**Comment by hcpss-banderson** [comment]
Maybe I could add an update hook to add the existing twitter and facebook urls. Right now, they would just be blank and no icons would show until an admin went in and updated them.

**Comment by hcpss-banderson** [comment]
... or maybe not because it looks like theme_update_N is not a thing.
If the accounts all follow the hcpss_[school-code] format, then I could set that as the default. Any chance that's the case?

**Comment by hcpss-banderson** [comment]
oops accidentally closed

**Comment by hcpss-mbarger** [comment]
Since we created all the school's Twitter accounts centrally, all their username's follow the hcpss_[school-subdomain] pattern.  Facebook accounts are created at the school level so they don't have a standard naming convention.

Should the Facebook value also be stored with https://github.com/HCPSS/schoolsite_deploy ?  Feels like a central site variable and not just a theme variable.  What do you think?

**Comment by hcpss-banderson** [comment]
I think you're right.

If we were talking about a custom module that needed to do a schema change then it should handle it internally, but what we are talking about here is really a deployment issue. So, yeah, it should go in the deployment module.

So, I am happy with this pull request, but it needs to be synced with a corresponding deployment update.

**Comment by hcpss-banderson** [comment]
As discussed, I removed the part that actually defines the social media link variables. The twitter link is now dynamically generated from the existing hcpss_school_code.

If a hcpss_facebook_url is available, then the facebook icon is displayed. But hcpss_facebook_url is not defined here I will implement that in a module.

**Pull request merged**
